# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/custom-placeholders/conditional-text
conditional-text:
  actionbar:
    priority_1:
      text: '%nameplates_background_other_actionbar%'
      conditions:
        '||':
          '!=':
            value1: '%player_remaining_air%'
            value2: "300"
          '!gamemode': survival
    priority_2:
      text: '%nameplates_static_money_hud%%nameplates_offset_-180%%nameplates_static_other_actionbar%'
      conditions:
        '!equals':
          value1: '%nameplates_actionbar%'
          value2: ""
    priority_3:
      text: '%nameplates_static_money_hud%'
  weather:
    priority_1:
      text: 'Sunny'
      conditions:
        weather:
          - clear
    priority_2:
      text: 'Rainy'
      conditions:
        weather:
          - rain
    priority_3:
      text: 'Thunder'
      conditions:
        weather:
          - thunder
    priority_4:
      text: 'Rainstorm'
      conditions:
        weather:
          - rainstorm

# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/custom-placeholders/nameplate-text
nameplate-text:
  halloween:
    nameplate: halloween
    text: '<gradient:#FFD700:#FFA500:#FFD700>Today is Halloween! Trick or treat!</gradient>'

# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/custom-placeholders/background-text
background-text:
  location:
    background: bedrock_1
    text: '%nameplates_image_compass% %nameplates_descent_location%'
    remove-shadow: true
  time:
    background: bedrock_1
    text: '%nameplates_image_clock% %nameplates_descent_time%'
    remove-shadow: true
  weather:
    background: bedrock_1
    text: '%nameplates_image_weather% %nameplates_descent_weather%'
    remove-shadow: true
  hello:
    background: bedrock_1
    text: '%nameplates_image_bubble% %nameplates_descent_hello%'
    remove-shadow: true
  update:
    background: bedrock_1
    text: '%nameplates_image_bell% %nameplates_descent_update%'
    remove-shadow: true
  other_actionbar:
    background: bedrock_2
    text: '%nameplates_actionbar%'
    remove-shadow: true

# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/custom-placeholders/static-text
static-text:
  money_hud:
    position: right
    text: '%nameplates_image_coin% %nameplates_descent_money%'
    value: 180
  other_actionbar:
    position: middle
    text: "%nameplates_background_other_actionbar%"
    value: 180

# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/custom-placeholders/descent-text
descent-text:
  location:
    text: "Your Location: %player_x%, %player_y%, %player_z%"
    descent: 5
    is-unicode: false
  time:
    text: "Time: %nameplates_time%"
    descent: 5
    is-unicode: false
  weather:
    text: "Weather: %nameplates_conditional_weather%"
    descent: 5
    is-unicode: false
  update:
    text: "A newer version of CustomNameplates is available!"
    descent: 5
    is-unicode: false
  money:
    text: "%vault_eco_balance%"
    descent: 23
    is-unicode: false
  hello:
    text: "Hello 여보세요 你好 こんにちは, Thanks for using CustomNameplates"
    descent: 5
    is-unicode: true

# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/custom-placeholders/switch-text
switch-text:
  season:
    switch: '%customcrops_season%'
    case:
      'Spring': '<green>Spring</green>'
      'Summer': '<yellow>Summer</yellow>'
      'Autumn': '<gold>Autumn</gold>'
      'Winter': '<blue>Winter</blue>'
    default: 'Invalid season'

# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/custom-placeholders/vanilla-hud
vanilla-hud:
  stamina_hud:
    reverse: true
    images:
      empty: stamina_0
      half: stamina_1
      full: stamina_2
    placeholder:
      value: '1.1'
      max-value: '2'