# Do not change
config-version: '25'

# Debug mode
debug: false

# bStats
metrics: true

# Check update
update-checker: true

# Language
# english/chinese/spanish/russian/turkish/french
lang: english

# Modules
modules:
  nameplates: true
  backgrounds: true
  bubbles: true
  bossbars: true
  actionbars: true
  images: true

# Integrations (Please read the wiki)
# https://mo-mi.gitbook.io/xiaomomi-plugins/plugin-wiki/customnameplates/compatibility
integrations:
  resource-pack:
    ItemsAdder: false
    ItemsAdder-old-method: false
    Oraxen: false
  team:
    unknown: false
    TAB: false
    CMI: false
    Velocitab: false
  chat:
    TrChat: false
    VentureChat: false

resource-pack:
  # disable resource pack generation on server start
  disable-generation-on-start: false
  # Namespace
  namespace: "nameplates"
  # Font name
  font: "default"
  # The initial character of the custom font
  # Although Korean is used here, it does not affect the normal use of Korean in chatting, as they are not in the same font
  initial-char: 'ÎÄÅ'
  # Customize the folder where png files should be generated.
  # This is useful for those who want to keep their resource pack structure in order.
  image-path:
    nameplates: 'font\nameplates\'
    backgrounds: 'font\backgrounds\'
    images: 'font\images\'
    bubbles: 'font\bubbles\'
    space-split: 'font\base\'

  shader:
    # Enable shaders
    enable: true
    # Hide scoreboard numbers
    hide-scoreboard-number: false
    # Add Animated text support
    animated-text: false
    # Add ItemsAdder text effect support
    ItemsAdder-text-effects: false

  transparent-bossbar:
    # Make a certain bossbar transparent
    color: YELLOW
    # Generate the transparent bossbar for 1.20.2+
    1_20_2+: true
    # Generate the transparent bossbar for legacy versions
    1_17-1_20_1: true

  # Legacy unicode Support for 1.20+ clients
  # This would make your resource pack about 900KB bigger
  legacy-unicodes: true

other-settings:
  # Disable CustomNameplates' team management
  # Never enable this if you are using "Team" mode for name tags
  disable-team-management: false

  # Create real teams on serverside. It's not recommended to enable this unless you meet BungeeCord team bugs.
  create-real-teams: false

  # It's recommended to use MiniMessage format. If you insist on using legacy color code "&", enable the support below.
  legacy-color-code-support: false

  # Thread pool settings
  thread-pool-settings:
    # The size of the core Thread pool, that is, the size of the Thread pool when there is no task to execute
    # Increase the size of corePoolSize when you are running a large server with many players fishing at the same time
    corePoolSize: 10
    # The maximum number of threads allowed to be created in the Thread pool. The current number of threads in the Thread pool will not exceed this value
    maximumPoolSize: 10
    # If a thread is idle for more than this attribute value, it will exit due to timeout
    keepAliveTime: 30

  # delay x ticks before actionbar/bossbar is sent to players
  send-delay: 0

  # Set the size for the cache system. This is useful and would bring huge performance improvement if you keep it to a reasonable value
  # Many developers don't seem to think that parsing text labels would incur significant performance overhead but actually it does through it's running asynchronously.
  # With cache system, you can save much CPU resource when the same message is displayed to many players.
  # The more people on your server, the higher the efficiency of the caching system's operation.
  # In most cases you don't have to edit this value. You can increase this value appropriately, especially when there are many players on your server.
  cache-size: 256